// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: address.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Person } from "./person";

export const protobufPackage = "test";

/** Our address book file is just one of these. */
export interface AddressBook {
  people: Person[];
}

function createBaseAddressBook(): AddressBook {
  return { people: [] };
}

export const AddressBook: MessageFns<AddressBook> = {
  encode(message: AddressBook, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.people) {
      Person.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddressBook {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddressBook();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.people.push(Person.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddressBook {
    return {
      people: globalThis.Array.isArray(object?.people) ? object.people.map((e: any) => Person.fromJSON(e)) : [],
    };
  },

  toJSON(message: AddressBook): unknown {
    const obj: any = {};
    if (message.people?.length) {
      obj.people = message.people.map((e) => Person.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddressBook>, I>>(base?: I): AddressBook {
    return AddressBook.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddressBook>, I>>(object: I): AddressBook {
    const message = createBaseAddressBook();
    message.people = object.people?.map((e) => Person.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
